### PR TITLE
Add `dplyr_reconstruct()` method

### PR DESCRIPTION
**Pull request by lionel-**
This method is used to restore the class of the output of `bind_rows()` and `bind_cols()` to the class of the first input.

With CRAN dplyr:

```r
sf1 = st_sf(x = 1, y = st_sfc(st_point(0:1)))
sf2 = st_sf(z = st_sfc(st_point(2:3)), x = 2)

bind_rows(sf1, sf2)
#> Error in .subset2(x, i, exact = exact) :
#>   attempt to select less than one element in get1index
#> In addition: Warning messages:
#> 1: In bind_rows_(x, .id) :
#>   Vectorizing 'sfc_POINT' elements may not preserve their attributes
#> 2: In bind_rows_(x, .id) :
#>   Vectorizing 'sfc_POINT' elements may not preserve their attributes
```

With dplyr 1.0:

```r
bind_rows(sf1, sf2)
#> Simple feature collection with 2 features and 1 field
#> Active geometry column: y (with 1 geometry empty)
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 0 ymin: 1 xmax: 0 ymax: 1
#> CRS:            NA
#>   x           y           z
#> 1 1 POINT (0 1) POINT EMPTY
#> 2 2 POINT EMPTY POINT (2 3)
```

### CODE REVIEW

**Comment by edzer** [comment]
This is fantastic, @lionel-  - thanks so much!!

**Comment by edzer** [comment]
With dplyr from github (master), I get
```
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 711 | SKIPPED: 58 | WARNINGS: 6 | FAILED: 4 ]
  1. Failure: bind_rows() returns type of first input (@test_tidy.R#129) 
  2. Failure: bind_rows() returns type of first input (@test_tidy.R#136) 
  3. Failure: bind_rows() returns type of first input (@test_tidy.R#144) 
  4. Failure: bind_rows() returns type of first input (@test_tidy.R#152) 
```
This is with vctrs from CRAN, does that also require a dev version?

**Comment by lionel-** [comment]
Ah it's possible, dev vctrs now uses `c.sfc()` to combine the sfc chunks to work around bugs in the ptype2.sfc implementations. I plan to release vctrs Friday at the latest, hopefully sooner.

**Comment by edzer** [comment]
Having vctrs installed from `r-lib/vctrs` and dplyr from `tidyverse/dplyr` leaves me with
```
Last 13 lines of output:
   5. vctrs::vec_default_ptype2(...)
   6. vctrs::stop_incompatible_type(...)
   7. vctrs:::stop_incompatible(...)
   8. vctrs:::stop_vctrs(...)
  
  Failed to create feature 1 in x
  Failed to create feature 1 in x
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 712 | SKIPPED: 58 | WARNINGS: 6 | FAILED: 3 ]
  1. Failure: `precision` and `crs` attributes of `sfc` vectors are combined (@test_vctrs.R#48) 
  2. Failure: `precision` and `crs` attributes of `sfc` vectors are combined (@test_vctrs.R#51) 
  3. Error: `sfc` vectors have a common type (@test_vctrs.R#59) 
  
```

**Comment by lionel-** [comment]
Ah yes, my installation of sf crashes when I run the tests, so I've only tested `test_tidy.R` locally and forgot to check `test_vctrs.R`. It probably needs an update, I'll follow up. Also for some reason the sample-n test now fails locally despite the `set.seed()`. I'll make it more robust by not checking details that depend on the sampling.

**Pull request merged**
