### PR TITLE
Fix restoration of sfc lists

### PR DESCRIPTION
**Pull request by lionel-**
Reverts #1335
Part of r-lib/vctrs#1136

cc @krlmlr

### CODE REVIEW

**Comment by mem48** [comment]
Confirmed this works

```
remotes::install_github("r-spatial/sf#1414", force = TRUE)
remotes::install_github("r-lib/vctrs#1137", force = TRUE)

library(sf)

xyz1 <- st_linestring(matrix(runif(18), ncol = 3))
xyz1 <- st_as_sf(data.frame(id = 1, geom = st_as_sfc(list(xyz1))))

xyz2 <- st_linestring(matrix(runif(18), ncol = 3))
xyz2 <- st_as_sf(data.frame(id = 2, geom = st_as_sfc(list(xyz2))))

res_xyz <- dplyr::bind_rows(list(xyz1, xyz2, xyz1))
```

But when I run the test on `opentripplanner` I now get a NOTE

```
> checking dependencies in R code ... NOTE
  Error in env_bind_impl(.env, list3(...), "env_bind()", bind = TRUE) : 
    cannot change value of locked binding for 'st_crs'
```

Any idea what this means?

**Comment by lionel-** [comment]
@mem48 Thanks for trying and reporting! This is an issue with the lazy importing of sf functions. This should be fixed with https://github.com/r-lib/vctrs/pull/1137/commits/5797453ea1f67b0b14b6ca0aa505b62b359423be, can you confirm please?

**Comment by mem48** [comment]
@lionel- yes that fixed the problems

**Comment by edzer** [comment]
Great, thanks - now merged!

**Pull request merged**
