### PR TITLE
Update sf7 vignette, more examples, add benchmarks, evaluate

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @edzer this is a remote and indirect contribution to OpenGeoHub, from the hills in north Wales. Not sure why it's failing on most set-ups but works on my laptop. I think the benchmark conveys the message: think about resolution!

**Comment by edzer** [comment]
Thanks a lot Robin! Yes, the tests are very noisy ATM and need maintenance.

**Comment by Robinlovelace** [comment]
Any feedback welcome

**Comment by edzer** [comment]
Great work, thanks. I'll try to extend it wrt

* s2 buffers being always cell boundaries
* using `sf_within_distance` rather than computing a buffer, then intersecting with the buffer

**Pull request merged**
