### PR TITLE
crs is lost in st_as_sfc.bbox

### PR DESCRIPTION
**Pull request by faridcher**
```r
st_as_sfc(st_bbox(st_linestring(matrix(1:4,2))), crs=4326)
```

### CODE REVIEW

**Comment by edzer** [comment]
Yes, but what if argument `crs` is different from the CRS of `x`? Why not use
```r
st_as_sfc(st_set_crs(st_bbox(st_linestring(matrix(1:4,2))), 4326))
```

**Comment by faridcher** [comment]
i think `st_set_crs` is too verbose and redundant. Why not just use st_as_sfc? I think `st_bbox(obj, ..., crs)` should support objects other than Extent and numeric so  `st_bbox(st_linestring(matrix(1:4,2)), crs=4326)` would work then.

**Comment by edzer** [comment]
You did not answer my first question.

**Comment by faridcher** [comment]
You are right. I wrote this patch when st_bbox did not support crs. `st_set_crs` works here but my above side makes st_bbox more flexible. thank you

**Pull request closed without merging**
