### PR TITLE
Tweak to ensure rwinlib compatibity with ucrt

### PR DESCRIPTION
**Pull request by jeroen**
Small tweak for future compatibility.

### CODE REVIEW

**Comment by edzer** [comment]
Great! I hope this will resolve the [error](https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/stars-00check.html) stars currently has on UCRT when reading a netcdf file (it does this by calling GDAL routines in `sf`).

**Comment by jeroen** [comment]
Yes I think it will. With this, the behaviour between the ucrt and non-ucrt builds should be 100% consistent.

**Comment by rsbivand** [comment]
Thanks Jeroen! I made the same tweak for **rgeos** rev 672 https://r-forge.r-project.org/scm/viewvc.php?root=rgeos&view=rev and **rgdal**  rev 1135 https://r-forge.r-project.org/scm/viewvc.php?root=rgdal&view=rev. Does that make sense?

**Comment by jeroen** [comment]
Yes that looks correct, thank you!

**Pull request merged**
