### PR TITLE
Clarify installation instructions

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by edzer** [comment]
Am I right this would imply we recommend using PROJ 4.9.3 on systems that still carry that? I don't agree.

**Comment by Robinlovelace** [comment]
Before it didn't provide any recommendation but I see what you mean. Do you agree with this?:

> To get more up-to-date versions of dependencies such as GDAL (recommended)

**Comment by edzer** [comment]
I would just go for saying "we recommend using the PPA". Indeed, it doesn't say so right now, the current text was written in 2017 when this was less of an issue (before the PROJ storm).

**Comment by Robinlovelace** [comment]
> I would just go for saying "we recommend using the PPA"

Done. Also tried to 'un-recommend' installing dependencies by source by adding the bit about 'advanced users'. Installing the OSGeo stack from source seems to cause problems.

**Comment by edzer** [comment]
OK, thanks!

**Pull request merged**
