### PR TITLE
Tweak Makevars.win for possible future toolchain

### PR DESCRIPTION
**Pull request by jeroen**
Small tweak that will make it easier to update to the next toolchain.

### CODE REVIEW

**Comment by jeroen** [comment]
@rsbivand could you make this same change in rgdal? I'm not sure what the appropriate way is to propose a patch in rforge.

**Comment by rsbivand** [comment]
Thanks, change made for **rgdal**, will commit shortly. Does **rgeos** need attention: https://r-forge.r-project.org/scm/viewvc.php/pkg/src/Makevars.win?view=markup&root=rgeos ?

**Comment by jeroen** [comment]
@rsbivand yes it would be nice if you could also update __rgeos__ to the gdal-2.2.3 build so that I no longer have to look after the gdal-2.2.0 build.

The easiest way to do this is copy 2 files [`src/Makevars.win`](https://github.com/r-spatial/sf/blob/6ca86b88be7615005358c024ffb2607d6569f718/src/Makevars.win) and [`tools/winlibs.R`](https://github.com/r-spatial/sf/blob/6ca86b88be7615005358c024ffb2607d6569f718/tools/winlibs.R) from rgdal into rgeos. Then perhaps you can remove the `-I` and `-L` and `-l` flags from `Makevars.win` which are unneeded for rgeos (though it's harmless having them in there, the linker will just ignore them).

**Comment by rsbivand** [comment]
Done for rgeos, committed to R-Forge.

**Comment by jeroen** [comment]
This PR can be merged ✅

**Comment by edzer** [comment]
Thanks a lot!

**Pull request merged**
