### PR TITLE
Fix compatible with tidyr 1.0.0

### PR DESCRIPTION
**Pull request by yutannihilation**
**DO NOT MERGE THIS**

Fixes https://github.com/r-spatial/sf/issues/1068

This PR will

* define `vec_proxy.sfc()` to make `unnest()` and `separate_rows()` work
* remove tests and examples that no longer work
* comment out `nest()` related codes until https://github.com/tidyverse/tidyr/pull/729 is merged

### CODE REVIEW

**Comment by edzer** [comment]
The comments say: uncomment this when https://github.com/tidyverse/tidyr/pull/729 is merged; despite that PR was merged, but we still see
```
> x <- storms.sf %>% group_by(name, year) %>% nest
Error: Quosures can only be unquoted within a quasiquotation context.

  # Bad:
  list(!!myquosure)

  # Good:
  dplyr::mutate(data, !!myquosure)
Call `rlang::last_error()` to see a backtrace
```
I'm merging this because it lets `sf` pass check with the released tidyr, but the issue is not solved. I appreciate any help!

**Comment by yutannihilation** [comment]
Aw, sorry for leaving this. Probably I should have removed `Remotes` after the release of tidyr v1.0.0.

> despite that PR was merged

tidyverse/tidyr#729 is not merged yet. So, it's better to keep commenting out the corresponding tests and examples. Do you plan to release the next sf immediately?

**Comment by edzer** [comment]
Planning to do so tomorrow -  the tidyr release will put it to 100% error on CRAN checks, so what else can I do?

**Comment by yutannihilation** [comment]
Sure, then I agree commenting out is the best choice for now because it probably needs some time to find how this should be fixed.

**Pull request merged**
