### PR TITLE
Support for SQLite (experimental)

### LINKED ISSUE #216: st_read_db and SQlite DB
Attempt to read from a sample sqlite db will fail while trying to read from an unexistent schema.

```R
link <- "https://www.gaia-gis.it/spatialite-2.3.1/test-2.3.zip"
temp <- tempfile()
download.file(link, temp)
tdir <- tempdir()
utils::unzip (temp, exdir = tdir)
unlink(temp)
db <- file.path(tdir, "test-2.3.sqlite")
dbcon <- dbConnect(dbDriver("SQLite"), db)
dbListTables(dbcon)
dbListFields(dbcon, "HighWays")
dbReadTable(dbcon, "HighWays", geom_column = 'Geometry' )
dbReadTable(dbcon, "geometry_columns")
lin = st_read_db(dbcon, "HighWays", geom_column = 'Geometry')
```
```R
> lin = st_read_db(dbcon, "HighWays", geom_column = 'Geometry')
Error in rsqlite_send_query(conn@ptr, statement) : 
  no such table: information_schema.views
```

### PR DESCRIPTION
**Pull request by etiennebr**
This PR provides experimental read support for sqlite. 

fix #216

### CODE REVIEW

**Comment by etiennebr** [comment]
Don't merge this yet please

**Comment by edzer** [comment]
Pls let me know if anything is happening here, otherwise I suggest to close it here.

**Comment by etiennebr** [comment]
Ok, yes. I'll reopen it once I'm ready.

Etienne

Le dim. 16 juil. 2017 à 14:31, Edzer Pebesma <notifications@github.com> a
écrit :

**Comment by jsta** [comment]
For people finding this page from search engines, SQLite can be brought into sf with the `RSQLite` package. See https://github.com/r-spatial/sf/blob/master/tests/read.R#L69

**Pull request closed without merging**
