### PR TITLE
Finish implementing vctrs methods for `sfc` vectors

### PR DESCRIPTION
**Pull request by lionel-**
* Restore `n_empty`, `crs`, and `precision` attributes.

* Add common type implementation for `sfc` objects. This finds the common class based on heuristics found in `c.sfc()`.

* Added a new `vctrs` help topic, so that argument names can be documented separately from the tidyverse ones.

### CODE REVIEW

**Comment by lionel-** [comment]
Should we move the vctrs methods into their own file `vctrs.R` or perhaps `tidyverse-vctrs.R`?

I'm now looking into other data types, it might make the source more easily browsable to keep the vctrs methods separate as we might end up with a non-trivial amount of those.

**Comment by edzer** [comment]
Yes, good idea!

**Comment by lionel-** [comment]
hmm, last Travis build failed when it shouldn't have:

```
  Error: processing vignette 'sf5.Rmd' failed with diagnostics:

   package or namespace load failed for 'tidyr':

    object 'cnd_bullets' not found whilst loading namespace 'vctrs'
```

This is because dev rlang and dev vctrs are temporarily in incompatible state.

Is it intended that Travis checks against dev rlang and dev vctrs? I was assuming we'd be testing against CRAN versions.

**Comment by yutannihilation** [comment]
It seems because some `r_github_packages` is used by default. I guess they were necessary for development at the time when they were added. Are they still needed now?

https://github.com/r-spatial/sf/blob/fe70feab8375147bfa4c8299496785051c7f08e7/.travis.yml#L19-L24

**Comment by lionel-** [comment]
Following up on https://github.com/r-spatial/sf/issues/1172#issuecomment-555911831, the CRS and precision attributes are now combined. I took the conservative approach of throwing an error if they are inconsistent. This can be changed to something more appropriate by modifying `common_crs()` and `common_prec()`.

**Comment by edzer** [comment]
Looks good -- thanks so much!

**Pull request merged**
