### PR TITLE
Update .travis.yml, use tic and automatic deployment of pkgdown site

### PR DESCRIPTION
**Pull request by pat-s**
#### Changes

* move ppa installations to `addons`
* build on oldrelease, release & devel (failures are allowed for r-devel)
* cache packages a
* automatic deployment of `pkgdown` site on every commit using `tic`. Preview [here](https://pat-s.github.io/sf/docs/).
* example build: https://travis-ci.org/pat-s/sf/builds/357620507

#### Notes

* `lwgeom` is installed with force on every build using its shipped binary as linking to the `postgis` installation sometimes causes issues
* pkgdown is deployed to `docs/` subdirectory of the `master` branch for every commit to `master`. 
* To use the `pkgdown` deployment, you need to call `travis::use_travis:deploy()` once to set up a ssh key pair with travis and change your Github pages settings in the repo to serve from `gh-pages`.
* Why `tic`? -> https://ropenscilabs.github.io/tic/; CI-agnostic workflow definitions and simplified pkgdown deployment

(You may want to [squash all commits into a single one](https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/))

### CODE REVIEW

**Comment by krlmlr** [comment]
This looks good. I was a proponent for a `gh-pages` branch for a long time, but these days I do recommend the `docs/` subdirectory, for the following reasons:

1. It's simpler.
1. Documentation changes/updates are linked to changes in the source.
1. You can preview changes to the rendered documentation if necessary.
1. If docs are hosted on Netlify, you can preview a pull request.
1. It's easier to use GitHub Pages to serve heavy files.

After merging, someone with write permissions needs to run `travis::use_travis_deploy()` (from ropenscilabs/travis) on a local clone of the *sf* repo, you mentioned that already.

**Comment by krlmlr** [comment]
This, and the download size increases. The benefits are worth more IMO.

**Comment by krlmlr** [comment]
For the first problem, there's `git l -- . ":^docs"`, see https://stackoverflow.com/a/21079437/946850.

**Comment by edzer** [comment]
I think this is a good idea, once this new approach has stabilised. travis works now, and I don't want to give this attention every week or so. Let me know when we're there.

**Comment by pat-s** [comment]
> For the first problem, there's git l -- . ":^docs", see https://stackoverflow.com/a/21079437/946850.

How would this behave in practice? The commits are still there and we need to pull them every time but we just do not see the commit in the git logs?

> It's simpler.
> Documentation changes/updates are linked to changes in the source.
> You can preview changes to the rendered documentation if necessary.
> If docs are hosted on Netlify, you can preview a pull request.
> It's easier to use GitHub Pages to serve heavy files.

Why is it simpler? 

Doc updates are also linked to changes in the source in the `gh-pages` branch via the "travis build XY", right?

Preview: The preview of PR might be a feature but I think this might not really be of any value for `sf`?
Do you mean previewing changes by running `pkgdown::build_site()` locally? I do not see how `docs/` lets you preview changes.

"Github pages" is used for serving both `docs/` or `gh-pages` branch?

@edzer Do you prefer serving from `docs/` or the `github-pages` branch?

**Comment by edzer** [comment]
@pat-s this is a feature of netlify, which can also be used to serve github pages, I guess after some custom forwarding; nice to have but not of much value now, afaict. It seems that if this setup makes commits itself, it would indeed be cleaner to have them committed to a gh-pages branch than to master?

**Comment by pat-s** [comment]
> It seems that if this setup makes commits itself, it would indeed be cleaner to have them committed to a gh-pages branch than to master?

This was also my point and I do it this way for all of my repos.  

I would consider the PR as "ready". Please have a look.
All the changes to `docs/` can be ignored (and merged). You can delete the `docs/` folder anyway after serving from `gh-pages`.

Remember to run `travis::use_travis_deploy()` once to set up the ssh keys for travis deployment :)

**Comment by edzer** [comment]
Pretty cool, @pat-s - works like a dream!

**Comment by pat-s** [comment]
Good to hear :-)

You can then safely delete the `docs/` dir in `master` and do not have to worry anymore about updating the `pkgdown` site :smiley:

**Comment by edzer** [comment]
@pat-s I'm seeing a false positive here: https://travis-ci.org/r-spatial/sf/jobs/372645395 -- could you pls check?

**Comment by edzer** [comment]
@pat-s any idea what is going wrong [here](https://travis-ci.org/r-spatial/sf/jobs/389676026)?

**Comment by tim-salabim** [comment]
I had the same error for a while, resolved itself with the last commit. Not very helpful, I know.

**Comment by pat-s** [comment]
As @tim-salabim said.
I also faced that issue. I thinks it's a Travis thing. Should solve itself in the next commits.

**Comment by edzer** [comment]
@pat-s any idea why auto-uploading the docs doesn't work anymore [since 24 days](https://github.com/r-spatial/sf/tree/gh-pages)?

**Comment by edzer** [comment]
I tried once more; the errors seem to originate from tic, afaics.

**Comment by pat-s** [comment]
This look like a bug, yes. I've opened an issue. 

https://github.com/ropenscilabs/tic/issues/56

**Pull request merged**
