### PR TITLE
GH-actions for macOS (#1309):

### PR DESCRIPTION
**Pull request by ateucher**
- add Rcpp drat repo to work around https://github.com/RcppCore/Rcpp/issues/1060
- add configure.args for sf and rgdal (hopefully only necessary temporarily: #1312)
- don't build vignettes on macOS

I'm not sure this gets it 100%, but we can see how far it gets and I should be able to debug from there...

@etiennebr

### CODE REVIEW

**Comment by ateucher** [comment]
@etiennebr I'm not sure if you have admin access here, but for some reason the actions aren't running for me (only on my first two commits). Any way you can trigger it manually?

**Comment by ateucher** [comment]
Actually scratch that, I can just watch on my fork

**Comment by ateucher** [comment]
@etiennebr @edzer the check on macOS R-release (https://github.com/r-spatial/sf/runs/546256574?check_suite_focus=true) is now runninag and producing similar errors to those on CRAN: https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/sf-00check.html.

**Comment by edzer** [comment]
The error is not the same; afaict it is pkg `tmaptools` that is missing, and needed for vignette 5.

**Comment by ateucher** [comment]
Sorry @edzer, I meant this error in running examples (which I also reproduce locally):

```
* checking examples ... ERROR
Running examples in 'sf-Ex.R' failed
The error most likely occurred in:

> ### Name: st_crs
> ### Title: Retrieve coordinate reference system from object
> ### Aliases: st_crs st_crs.sf st_crs.numeric st_crs.character st_crs.sfc
> ###   st_crs.bbox st_crs.CRS st_crs.crs st_crs<- st_crs<-.sf st_crs<-.sfc
> ###   st_set_crs NA_crs_ is.na.crs $.crs format.crs st_axis_order
> ### Keywords: datasets
> 
> ### ** Examples
> 
> sfc = st_sfc(st_point(c(0,0)), st_point(c(1,1)))
> sf = st_sf(a = 1:2, geom = sfc)
> st_crs(sf) = 4326
> st_geometry(sf)
Geometry set for 2 features 
geometry type:  POINT
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 1 ymax: 1
CRS:            EPSG:4326
POINT (0 0)
POINT (1 1)
> sfc = st_sfc(st_point(c(0,0)), st_point(c(1,1)))
> st_crs(sfc) = 4326
> sfc
Geometry set for 2 features 
geometry type:  POINT
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 1 ymax: 1
CRS:            EPSG:4326
POINT (0 0)
POINT (1 1)
> sfc = st_sfc(st_point(c(0,0)), st_point(c(1,1)))
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> x = sfc %>% st_set_crs(4326) %>% st_transform(3857)
> x
Geometry set for 2 features 
geometry type:  POINT
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 111319.5 ymax: 111325.1
CRS:            EPSG:3857
POINT (0 0)
POINT (111319.5 111325.1)
> st_crs("EPSG:3857")$input
[1] "EPSG:3857"
> st_crs("+init=epsg:3857")$proj4string
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
[1] "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"
> st_crs("+init=epsg:3857 +units=m")$b     # numeric
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
Error in st_crs.character("+init=epsg:3857 +units=m") : 
  invalid crs: +init=epsg:3857 +units=m
Calls: st_crs -> st_crs.character
Execution halted
```

That other one is spurious I think.

**Comment by ateucher** [comment]
Ok I have the checks on macOS (r-release and r-devel) down to just producing the error (failed example) that is the same as the error on the CRAN checks. @etiennebr has a simple fix ([here](https://github.com/etiennebr/sf/commit/9aacb6578c5fbf246e304b1072592db563f41182)), which I could incorporate into this PR if you like?

**Comment by edzer** [comment]
Yes, that would be great!

**Comment by etiennebr** [comment]
Good job @ateucher! :tada: 

@edzer, if you want to perform a single review I could merge this branch in 'gh-actions', but I don't see any problem in merging this branch right away since it keeps all travis, appveyor and codecov checks, but adds linux and macOS checks.

@ateucher, are there any lessons we could use to improve the installation instructions for macOS?

**Comment by ateucher** [comment]
Whew that was a messy one. I definitely recommend doing a "squash and merge"! I also think this could be merged into master.

@etiennebr yes definitely, I plan on making a PR to the README to update the macOS install instructions. The Rcpp bug has thrown an extra wrench in the works, but hopefully that won't take too long to get to CRAN. The configure.args etc on its own is relatively straightforward...

**Comment by edzer** [comment]
If someone could help to squash this before I merge, the would be great!

**Comment by ateucher** [comment]
@edzer I usually use the "squash and merge" option in the dropdown in the green merge button. Then you can edit the commit message (I'd probably make it something like):

```
Add GitHub actions for macOS
* split actions into two files - one for testing with Postgres and one for macOS/Windows
* fix example that was causing errors
```

Or I can give it a go locally, then force-push, whichever you'd prefer!

**Comment by ateucher** [comment]
Actually this history is a mess. I'm going to create a new branch and PR...

**Comment by ateucher** [comment]
Closing in favour of #1330

**Pull request closed without merging**
