### PR TITLE
Update macOS install instructions in README

### LINKED ISSUE #1401: macOS install instructions
I am able to install {sf} 0.9-3 from source on macOS without the need for custom `configure.args`.

With 

- proj 7.0.1
- gdal 2.4.4_6
- geos 3.8.1_1

on R 4.0.0 on latest macOS 10.15.4 

`proj`, `gdal` and `geos` installed (and linked) via `brew`. No custom Makevars set.
Might be worth updating the install instructions in the README?

<details>
<summary>Details</summary>

```r
configure: CC: ccache clang
configure: CXX: ccache clang++ -std=gnu++11
checking for gdal-config... /usr/local/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.4.4
checking GDAL version >= 2.0.1... yes
checking for gcc... ccache clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether ccache clang accepts -g... yes
checking for ccache clang option to accept ISO C89... none needed
checking how to run the C preprocessor... ccache clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/Cellar/gdal/2.4.4_6/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 2.4.4
configure: pkg-config proj exists, will use it
configure: using proj.h.
configure: PROJ: 7.0.1
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
checking for geos-config... /usr/local/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.8.1
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/local/Cellar/geos/3.8.1_1/lib -lgeos_c... yes
configure: Package CPP flags:  -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include
configure: Package LIBS: -L/usr/local/Cellar/proj/7.0.1/lib -lproj   -L/usr/local/Cellar/gdal/2.4.4_6/lib -lgdal -L/usr/local/Cellar/geos/3.8.1_1/lib -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c bbox.cpp -o bbox.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c gdal.cpp -o gdal.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c gdal_geom.cpp -o gdal_geom.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c gdal_read.cpp -o gdal_read.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c gdal_utils.cpp -o gdal_utils.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c gdal_write.cpp -o gdal_write.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c geos.cpp -o geos.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c hex.cpp -o hex.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c ops.cpp -o ops.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c polygonize.cpp -o polygonize.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c proj.cpp -o proj.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c proj_info.cpp -o proj_info.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c raster2sf.cpp -o raster2sf.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c sfg.cpp -o sfg.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c signed_area.cpp -o signed_area.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c stars.cpp -o stars.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c wkb.cpp -o wkb.o
ccache clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.0.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/2.4.4_6/include -I/usr/local/Cellar/geos/3.8.1_1/include -I'/Users/pjs/Library/R/4.0/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c zm_range.cpp -o zm_range.o
ccache clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o sf.so RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfg.o signed_area.o stars.o wkb.o zm_range.o -L/usr/local/Cellar/proj/7.0.1/lib -lproj -L/usr/local/Cellar/gdal/2.4.4_6/lib -lgdal -L/usr/local/Cellar/geos/3.8.1_1/lib -lgeos_c -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
in method for ‘dbWriteTable’ with signature ‘"PostgreSQLConnection","character","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘dbDataType’ with signature ‘"PostgreSQLConnection","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘coerce’ with signature ‘"Spatial","sf"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"Spatial","sfc"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sf","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sfc","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"XY","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"crs","CRS"’: no definition for class “CRS”

```

</details>

### PR DESCRIPTION
**Pull request by pat-s**
fixes #1401

### CODE REVIEW

**Comment by ateucher** [comment]
Homebrew core is now updated to GDAL 3.1.0, GEOS 3.8.1 and PROJ 7.0.1. I installed sf (and rgdal) from source using those libraries with no `--configure.args` and no ENV vars for `PKG_CONFIG`, `GDAL_DATA` etc. From my experience, I would stay away from the osgeo tap due to its history of instability (as discussed in #1401), especially now since core is up to date.

**Comment by pat-s** [comment]
> Homebrew core is now updated to GDAL 3.1.0, GEOS 3.8.1 and PROJ 7.0.1. 

This was one reason why I opened this PR.

> I installed sf (and rgdal) from source using those libraries with no --configure.args and no ENV vars for PKG_CONFIG, GDAL_DATA etc. From my experience, I would stay away from the osgeo tap due to its history of instability (as discussed in #1401), especially now since core is up to date. 

I don't quite understand.
The change recommends homebrew-core by default and only mentions the osgeo4mac tap.

**Comment by ateucher** [comment]
> The change recommends homebrew-core by default and only mentions the osgeo4mac tap.

Yup, I see that - I'm just not sure it's worth mentioning the osgeo tap at all. One more (at least semi-redundant) set of instructions to maintain.

**Comment by pat-s** [comment]
> One more (at least semi-redundant) set of instructions to maintain.

I see the point. However, I see the mention more as a minimal acknowledgement to the maintainers of osgeo4mac (and a pointer to all their other available formulas).

The instructions are generic and should not really come with a maintenance burden.
Let's see what Edzer's view is 🙂

**Comment by edzer** [comment]
I hope you come to an agreement, because I'm not a mac user. I suggest to give one robust advice for installing from source, rather than multiple options. I hope the rather random but dominantly failing GH actions reports from OSX will also go away; many of them say sth like `proj.db not found`, indicating proj installation problems.

**Comment by pat-s** [comment]
> I hope you come to an agreement, because I'm not a mac user. I suggest to give one robust advice for installing from source, rather than multiple options.

There is one main approach since ever I'd argue (= homebrew-core) which was broken for some time due to the known gdal & proj version jumps and the recent rgdal blocker.

I think it's worth at least mentioning `osgeo4mac` as an **alternative** here.
But again: I am not the maintainer and wording and mentioning alternatives are always subjective decisions.
Feel free to adjust the text to your liking and remove parts.
This PR aimed to be a quick help and was not indented to raise a discussion about mentioning alternatives or not :)

> I hope the rather random but dominantly failing GH actions reports from OSX will also go away; many of them say sth like proj.db not found, indicating proj installation problems.

This is presumably because {rgdal} does not get installed properly from source, see: https://github.com/r-spatial/sf/pull/1430/checks?check_run_id=787768151#step:10:73

See also the differences in the linked version between {rgdal} and {sf}:

- https://github.com/r-spatial/sf/pull/1430/checks?check_run_id=787768151#step:11:79
- https://github.com/r-spatial/sf/pull/1430/checks?check_run_id=787768151#step:11:81

**Comment by ateucher** [comment]
I don't feel overly strongly about not including the alternative, but possibly it could be made clear that the homebrew core gdal is the recommended way?

@edzer regarding the macOS failures, with the updated GDAL and PROJ we no longer need to supply `configure.args` or set any ENV vars - I can do a PR to clean that up if you'd like? The only question I have is that when installing from source I get this one line that I'm not sure about:

```
checking GDAL: /usr/local/Cellar/gdal/3.1.0/share/gdal/pcs.csv readable... no
```
 After installing I get this:

```
sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.1"        "3.1.0"        "7.0.1"         "true"         "true" 
```

and everything seems to work fine.

**Comment by pat-s** [comment]
> with the updated GDAL and PROJ we no longer need to supply configure.args or set any ENV vars- I can do a PR to clean that up if you'd like?

Why another one if this is already done in this PR here?

**Comment by ateucher** [comment]
I meant a PR to change the GitHub Actions, and I was just offering to help out with that

**Comment by edzer** [comment]
@ateucher it would be great if you could update (simplify) the GH Actions formulae
@pat-s I am against listing a second brew-like option to do maintainers a favour; our first advice is already and will remain to install OSX binaries from CRAN.

**Comment by ateucher** [comment]
@edzer I think I did that it #1435 - unless you see there is more that could be simplified?

**Comment by pat-s** [comment]
@edzer Feel free to adjust the proposed text changes. If you want to phrase this entirely yourself, feel free to close here. No big deal ;)

**Comment by pat-s** [comment]
Because I am quite unsure if another rewrite here would lead to a merge, I won't put in more time but instead close this PR because it won't be merged in its current state anyways. Feel free to adapt/cherry-pick.

**Pull request closed without merging**
