### PR TITLE
Jeroen gdal3 rwinlib

### PR DESCRIPTION
**Pull request by edzer**

### CODE REVIEW

**Comment by jeroen** [comment]
FYI, I'll be on vacation until Mar 13, we can pick it up after that. In the mean time, perhaps it would be wise to run a revdep check on Windows to test for any unexpected breakage in dependent packages. That gives us a bit more testing coverage to ensure that the new rwinlib stack is stable.

**Comment by mdsumner** [comment]
I'm finally in a place where I can check this, so far so good ...

**Comment by edzer** [comment]
Great work -- I think this is ready to go. Any objections?

**Comment by jeroen** [comment]
I think this is good 👍 Will rgdal switch switch as well ?

**Comment by rsbivand** [comment]
Thanks for the heavy lifting @jeroen, yes. I have a win 10 R 4.0.0 machine
to try things out. Is it mostly changing the download link and the linking
flags?

Roger Bivand
Falsensvei 32
5063 Bergen

lør. 25. apr. 2020, 11:59 skrev Jeroen Ooms <notifications@github.com>:

**Comment by jeroen** [comment]
Yes, the required changes are in my original PR here (which edzer further tweaked in this PR): https://github.com/r-spatial/sf/pull/1274/files

**Comment by mdsumner** [comment]
@jeroen are you planning to separate PROJ for 6.3.1 so it's independent? I found issues with 6.1.0 so it would be good to have 6.3.1 on its own independent of this gdal bundle

**Comment by jeroen** [comment]
@mdsumner what do you mean? Would you like me to host a copy of just proj 6.3.1 on https://github.com/rwinlib/proj ?

**Comment by mdsumner** [comment]
Yes, thank you

**Comment by jeroen** [comment]
@mdsumner OK I've added a copy and made a PR for you: https://github.com/hypertidy/PROJ/pull/22

**Comment by rsbivand** [comment]
@jeroen Is it possible to detect and condition on the RTools version that the user is running? I'm afraid that people with an RTools will accept install from source on Windows, and we'll get errors reported in because they are mixing versions? Can we use that to pick GDAL3 or GDAL2, and whch set of `PKG_LIBS` to go with?

**Comment by jeroen** [comment]
@rsbivand don't worry, the binaries in rwinlib are compatible with both the old and new toolchain.

**Comment by rsbivand** [comment]
Thanks! Current devel **rgdal** Win binaries built using GDAL 3.0.4 and PROJ 6.3.1 linked from https://stat.ethz.ch/pipermail/r-sig-geo/2020-April/028063.html

**Comment by rsbivand** [comment]
@jeroen On running revdeps for **sp**, **rgdal** and **raster**, I'm seeing three fatal errors: `fatal error: gsl/gsl_rng.h: No such file or directory` in **hSDM**, **jSDM** and **landsepi**. In the latter case, https://gitlab.paca.inrae.fr/CSIRO-INRA/landsepi/-/blob/master/tools/winlibs.R seems to want to extract GSL from the GDAL2 archive.**jSDM** depends on RcppGSM, and **hSDM** expects GSL to be installed; both declare GSL a system requirement. I guess I haven't installed GSL properly, will check. Otherwise, **imager** says `fatal error: tiffio.h: No such file or directory`, but again, I guess I haven't followed up a system requirement. On balance, nothing related to the GDAL2/3 switch. I'm revdeping about 900 packages, so only 4 anomalies isn't bad. So no red lights, I think.

**Comment by jeroen** [comment]
@rsbivand those are packages that have system dependencies that are not automatically installed. If you are using rtools40 you can install those sysdeps as follows:

```sh
pacman -S mingw-w64-{i686,x86_64}-gsl
pacman -S mingw-w64-{i686,x86_64}-libtiff
```

Afterwards you should be able to check the above packages in R 4.0.

**Pull request merged**
