### PR TITLE
add as_tibble

### PR DESCRIPTION
**Pull request by kendonB**

### CODE REVIEW

**Comment by edzer** [comment]
Isn't `as_tibble` supposed to return a `tbl_df`, rather than an `sf` object? Wouldn't you expect it to de-sf an object? `as.data.frame.sf` now de-sf-s an `sf`,`data.frame` object.

**Comment by kendonB** [comment]
`as_tibble` tibbleizes `data.table`s (as in, creates a `tbl_dt`), so I would also expect it to tibbleize an `sf` `data.frame` also.

**Comment by kendonB** [comment]
@krlmlr, what should the behavior be?

**Comment by krlmlr** [comment]
I'd expect it to de-sf indeed, just like `as.data.frame.tibble` un-tibbleizes. You can implement using something like

```r
new_tibble(x, nrow = nrow(x))
```

. This keeps the geometry column.

**Pull request closed without merging**
