### PR TITLE
Travis: Fix false positives in R cmd check and deployment issues

### PR DESCRIPTION
**Pull request by pat-s**
Both forks solves the issues above. Tested in `mlr`.
Hotfix until PRs are merged in both repos.

### CODE REVIEW

**Comment by pat-s** [comment]
Hm, apparently it does still not catch the test failures in `sf`. Investigating. Please don't merge yet.

**Comment by pat-s** [comment]
Ok, works now as expected. The error is catched!

**Comment by edzer** [comment]
Travis still fails on all three platforms.

**Comment by pat-s** [comment]
Yes, but that's how it should be because it catches errors in the tests. These errors were not catched before - > false positives green travis build. 

The error which is related to an outdated GEOS version should be solved in another PR.

**Comment by edzer** [comment]
Excellent - thanks a lot!

**Pull request merged**
