### PR TITLE
st_example

### PR DESCRIPTION
**Pull request by etiennebr**
This is my proposal following discussion in #558. I exposed both `sf::` and `st_example()` ways, and I'd be happy to have your thoughts on it. `sf:` also works, @edzer talked about `sf_example()`, but I thought it might be more consistent to use the standard `st_` prefix so it gets suggested when pressing tab.

### CODE REVIEW

**Comment by etiennebr** [comment]
appveyor tries to upload outdated packages
```
Rscript -e 'options(repos=c(CRAN="https://cran.rstudio.com")); remotes::install_deps(dependencies = TRUE, type="both")'
[...]

 There are binary versions available (and will be installed) but the
  source versions are later:
          binary  source
digest    0.6.14  0.6.15
knitr       1.18    1.19
mapview    2.2.0   2.3.0
spatstat  1.54-0  1.55-0
spData   0.2.6.9 0.2.7.0
tidyr      0.7.2   0.8.0
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/knitr_1.18.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/knitr_1.18.zip': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package 'knitr' failed
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/spatstat_1.54-0.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/spatstat_1.54-0.zip': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package 'spatstat' failed
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/spData_0.2.6.9.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/spData_0.2.6.9.zip': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package 'spData' failed 
```
And then it fails to check package dependencies
```
* checking package dependencies ... ERROR
Packages suggested but not available: 'spatstat' 'knitr'
The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.
```
I'm not sure how to solve this.

**Comment by etiennebr** [comment]
Am I just unlucky with CI or there really is something wrong with this code? It passed on `oldrel` but not on `release` after 6 minutes (it took nearly 40 minutes to complete on `oldrel`) it failed on something that seems unrelated.
```
[31;1mThe command "curl -fLo /tmp/texlive.tar.gz https://github.com/jimhester/ubuntu-bin/releases/download/latest/texlive.tar.gz" failed and exited with 56 during .[0m

Your build has been stopped.
```

**Comment by edzer** [comment]
Yeah, travis has some hick-ups now and then.

**Comment by etiennebr** [comment]
This is a proposal, so feel free to suggest improvements.

**Comment by edzer** [comment]
I'm sorry, I'm going to drop this idea.

**Pull request closed without merging**
