### PR TITLE
Use latest version of tic

### PR DESCRIPTION
**Pull request by pat-s**
@krlmlr did a lot of work lately and fixed most of the issues. I cannot fully guarantee that this version is fully stable now but we are close to a CRAN release.

@edzer You can use this branch to solve the test errors. The `tic` implementation looks fine. 

I also tidied the DESCRIPTION using `usethis::use_tidy_description()`

### CODE REVIEW

**Comment by edzer** [comment]
Still some issues, looks like tic related to me: https://travis-ci.org/r-spatial/sf/jobs/428628046

**Comment by pat-s** [comment]
Yes, saw it.

Works locally, hm. Do you know what the `nativeRoutines` refers to? https://travis-ci.org/r-spatial/sf/jobs/428628046#L5445

Some c++ stuff that is missing here? The error is thrown from `pkgdown::build_site()`. Atm I don't think its an tic issue but rather travis related.

**Comment by krlmlr** [comment]
Maybe it would help to avoid stashing in pre-deploy: see link at https://travis-ci.org/r-spatial/sf/jobs/428628046#L5232 .

This might be a good default for `.travis.yml`, too.

**Comment by edzer** [comment]
Any news here, @pat-s ? Would like to get this working.

**Comment by pat-s** [comment]
Still trying, unsure why the `sf` installation in the deploy step fails.

It could be caused because its installed in a new R process and this process is missing some c++ deps, i.e. the "native routines" error. Currently trying to force installation in the same R process.

PS: The stage of the PR you just merged included a duplicate "version" field in the DESCRIPTION by accident.

**Comment by edzer** [comment]
@etiennebr I now see errors coming from tests you wrote: https://travis-ci.org/r-spatial/sf/builds/432212868 could you pls take a look?

**Comment by pat-s** [comment]
`new_process = F` didn't help.
Atm I have no clue where the error comes from and why it appears.
I don't think its related to *tic* (maybe *pkgdown* or travis itself).
Deployment and *pkgdown* currently works for all repos besides *sf*.

Do you know where this "nativeRoutines" error might come from? It seems to look for a dll file in `src` that can't be found.

**Comment by pat-s** [comment]
@edzer Trying to run the `pkgdown` stuff manually later (without the custom tic step). Not expecting that anything changes but lets see.

If that doesn't help we can try to run this step on appveyor (to see if its a travis thing).

**Comment by edzer** [comment]
The `nativeRoutines` stuff had apparently to do with r-devel;l now deploying under release, which works. Thanks!

**Comment by pat-s** [comment]
ahh, all that checking and in the end its sth that trivial - well, glad that it works now (hopefully for a longer time ;)!

**Comment by edzer** [comment]
I now see in various repos a break at random points with:
```
Error: HTTP error 403.
  API rate limit exceeded for 104.154.120.187. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
does this have anything to do with tic?

**Comment by krlmlr** [comment]
Thanks, I'm seeing it too in _tibble_, but thought this is some random error.

@gaborcsardi: Do you see a reason why `GITHUB_PAT` would be ignored now when using `remotes::install_github()` ? I've seen that the message that the env var is used is no longer printed, but it should still work?

**Comment by gaborcsardi** [comment]
It _should_. There was a mishap with it in the dev version, but AFAIK this was fixed  for the CRAN version. @jimhester ?

**Comment by pat-s** [comment]
I assume it is related to https://github.com/klutometis/roxygen/issues/822.

We have a workaround for this already, let me do a quick test.

**Comment by pat-s** [comment]
I was right. Opened PRs in the respective repos.

**Comment by edzer** [comment]
Hi @pat-s , any idea what is going wrong here? https://travis-ci.org/r-spatial/sf/jobs/537456557

**Comment by pat-s** [comment]
The error message looks a bit strange but I hope that #1058 solves it.  
The old (manual) approach should actually still work but the error message from the build above is new to me.

**Comment by edzer** [comment]
Thanks a lot!!

**Pull request merged**
