### PR TITLE
Resolve UBSAN error in wkb_read

### LINKED ISSUE #1152: new UBSAN errors in 0.8-0
See https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/sf/00check.log ; @dbaston this must be caused by https://github.com/r-spatial/sf/commit/34e59a810b26e23588378c3f6ba232509063cefe; could you please address it?

### PR DESCRIPTION
**Pull request by dbaston**
This should resolve #1152 . I tested it using the `rocker/r-devel-san` container.

### CODE REVIEW

**Comment by edzer** [comment]
Thanks a lot!!

**Comment by dbaston** [comment]
It might be nice to integrate this kind of testing into Travis, but to do it efficiently requires keeping an up-to-date build environment on Docker Hub. (We do this for PostGIS).

Or maybe the compiled portions of sf change infrequently enough that I should just do this testing offline.

**Comment by edzer** [comment]
For now: the second: this is the second time ubsan complained in 3 years. 

The [valgrind errors](https://cran.r-project.org/web/checks/check_results_edzer.pebesma_at_uni-muenster.de.html#sf) are trickier: many of them are noise, problems elsewhere, or triggered by intentional read/write errors where I'm not sure they can be solved on the sf side at all. I tend to put them off for CRAN, potentially for the wrong reason.

**Comment by rsbivand** [comment]
Maybe crosscheck with [valgrind errors](https://www.stats.ox.ac.uk/pub/bdr/memtests/valgrind/rgdal/rgdal-Ex.Rout) for **rgdal**?

**Pull request merged**
